### PR TITLE
Fix xts in long_to_ts

### LINKED ISSUE #76: xts support in read_ts broken
long_to_ts line 25 should be
```
list(ts_object = list(xts(value, order.by = as.yearmon(date_zoo))))
```

### PR DESCRIPTION
**Pull request by HomoCodens**
Fixes #76

### CODE REVIEW

File: R/import_helpers.R [hunk 1]
```diff
@@ -22,7 +22,7 @@ long_to_ts <- function(data) {
   dt_of_lists <- data_dt[, {
     dT <- diff(date_zoo)
     if(any(diff(dT) > 1e-6)) {
-      list(ts_object = list(xts(value, order_by = date_zoo)))
+      list(ts_object = list(xts(value, order.by = as.yearmon(date_zoo))))
```
Comment (mbannert) [inline R/import_helpers.R]: can we always use this? or do we need as.yearqtr as well?

Comment (HomoCodens) [reply R/import_helpers.R]: Actually I'm not even sure we need `as.yearmon` here. date_zoo should already be either yearmon or yearqtr by line 25 (lines 19-20). Need to try and find a suitable test case.

We only use xts in case of irregular time series anyway `any(diff(dT) > 1e-6)`, otherwise we return a ts (line 27).

Comment (HomoCodens) [reply R/import_helpers.R]: ... except we essentially unclass them with `as.numeric`.
